#!/bin/bash

DISQUE_DIR="/tmp/disq/disque-master"
DISQUE_CMD="${DISQUE_DIR}/src/disque"

disque_kill () {
    for i in $@; do
        ${DISQUE_CMD} -p $i shutdown >/dev/null 2>&1
    done
    echo 'Cluster destroyed'
}

disque_kill $@
